# frozen_string_literal: true

# Currently doesn't work with Appraisal 2.5.0 and Ruby >= 3.2
# customize_gemfiles do
#   {
#     heading: <<~HEADING
#       # frozen_string_literal: true
#
#       `%<gemfile>s` has been generated by Appraisal, do NOT modify it or `%<lockfile>s` directly!
#       Make the changes to the "%<appraisal>s" block in `Appraisals` instead.
#     HEADING
#   }
# end

appraise "rack-3-1" do
  gem "rack", "~> 3.1.0"
end

appraise "rack-3-2" do
  gem "rack", "~> 3.2.0"
end
