name: CI

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rubocop
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          [
            { version: "3.2", gemfile: rack_3_1 },
            { version: "3.2", gemfile: rack_3_2 },
            { version: "3.3", gemfile: rack_3_1 },
            { version: "3.3", gemfile: rack_3_2 },
            { version: "3.4", gemfile: rack_3_1 },
            { version: "3.4", gemfile: rack_3_2 },
          ]
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.ruby.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby.version }}
      - run: bundle exec rake spec
